import { WidgetSettingField } from '../types';

const field = (key: string, label: string, type: WidgetSettingField['type'], defaultValue: unknown, section: WidgetSettingField['section'] = 'Contenu', options?: Record<string, string>, description?: string): WidgetSettingField => ({ key, label, type, default: defaultValue, section, options, description });
const commonColor = field('color', 'Couleur', 'color', 'accent', 'Couleurs', undefined, 'Couleur CSS ou alias accent, muted, normal.');
const commonSize = field('size', 'Taille', 'select', 'medium', 'Affichage', { small: 'Petit', medium: 'Moyen', large: 'Grand' });

export const widgetSettings: Record<string, WidgetSettingField[]> = {
	quote: [field('source', 'Source', 'select', 'builtin', 'Contenu', { builtin: 'Intégrée', file: 'Fichier du vault', inline: 'Liste inline' }), field('file', 'Fichier', 'text', 'Citations.md', 'Contenu'), field('lang', 'Langue', 'select', 'fr', 'Contenu', { fr: 'Français', en: 'Anglais', all: 'Toutes' }), field('category', 'Catégorie', 'select', 'all', 'Contenu', { all: 'Toutes', motivation: 'Motivation', sagesse: 'Sagesse', science: 'Science', littérature: 'Littérature', humour: 'Humour' }), field('mode', 'Mode', 'select', 'daily', 'Contenu', { daily: 'Une par jour', random: 'Aléatoire' }), field('font', 'Police', 'font', 'serif', 'Police'), field('size', 'Taille', 'text', 'medium', 'Police'), field('weight', 'Graisse', 'select', 'normal', 'Police', { normal: 'Normale', bold: 'Gras', '300': '300', '500': '500', '700': '700', '900': '900' }), field('style', 'Style', 'select', 'normal', 'Police', { normal: 'Normal', italic: 'Italique' }), field('author-font', 'Police auteur', 'font', 'sans', 'Police'), field('author-size', 'Taille auteur', 'text', 'small', 'Police'), field('author-weight', 'Graisse auteur', 'select', 'normal', 'Police', { normal: 'Normale', bold: 'Gras', '500': '500', '700': '700' }), field('author-style', 'Style auteur', 'select', 'normal', 'Police', { normal: 'Normal', italic: 'Italique' }), field('align', 'Alignement', 'select', 'left', 'Affichage', { left: 'Gauche', center: 'Centre' }), field('author', 'Afficher l’auteur', 'toggle', true, 'Affichage'), field('border', 'Contour', 'toggle', true, 'Affichage'), field('bar', 'Barre', 'toggle', true, 'Affichage'), field('text-color', 'Couleur texte', 'color', 'normal', 'Couleurs'), field('author-color', 'Couleur auteur', 'color', 'muted', 'Couleurs'), field('border-color', 'Couleur contour', 'color', 'accent', 'Couleurs'), field('bar-color', 'Couleur barre', 'color', 'accent', 'Couleurs'), field('background', 'Fond', 'color', 'transparent', 'Couleurs'), commonColor],
	flipclock: [field('mode', 'Mode', 'select', 'clock', 'Contenu', { clock: 'Horloge', timer: 'Minuteur', stopwatch: 'Chronomètre' }), field('format', 'Format', 'select', '24', 'Affichage', { '24': '24 heures', '12': '12 heures' }), field('ampm', 'Afficher AM/PM', 'toggle', true, 'Affichage'), field('leading-zero', 'Zéro initial', 'toggle', true, 'Affichage'), field('timezone', 'Fuseau horaire', 'text', 'local', 'Contenu'), field('seconds', 'Afficher les secondes', 'toggle', true, 'Affichage'), field('hours', 'Heures', 'select', 'auto', 'Affichage', { auto: 'Automatique', show: 'Toujours', hide: 'Masquées' }), field('duration', 'Durée', 'text', '00:25:00', 'Contenu'), field('autostart', 'Démarrer automatiquement', 'toggle', false, 'Affichage'), field('on-finish', 'À la fin', 'select', 'sound', 'Affichage', { none: 'Rien', notice: 'Notification', sound: 'Son', both: 'Notification et son' }), field('loop', 'Répéter', 'toggle', false, 'Affichage'), field('laps', 'Activer les tours', 'toggle', true, 'Affichage'), field('id', 'Identifiant', 'text', '', 'Contenu'), commonSize, commonColor, field('textColor', 'Couleur du texte des cartes', 'color', 'normal', 'Couleurs'), field('cardColor', 'Couleur des cartes', 'color', 'accent', 'Couleurs')],
	clock: [field('format', 'Format', 'select', '24', 'Affichage', { '24': '24 heures', '12': '12 heures' }), field('ampm', 'Afficher AM/PM', 'toggle', true, 'Affichage'), field('leading-zero', 'Zéro initial', 'toggle', true, 'Affichage'), field('seconds', 'Afficher les secondes', 'toggle', true, 'Affichage'), field('timezone', 'Fuseau horaire', 'text', 'local', 'Contenu'), field('label', 'Libellé', 'text', 'Heure locale', 'Contenu'), commonColor],
	countdown: [field('date', 'Date', 'date', '', 'Contenu'), field('label', 'Libellé', 'text', 'Échéance', 'Contenu'), field('icon', 'Icône', 'text', '⏳', 'Contenu'), commonColor],
	progress: [field('period', 'Période', 'select', 'day', 'Contenu', { day: 'Jour', week: 'Semaine', month: 'Mois', year: 'Année' }), field('label', 'Libellé', 'text', 'Progression', 'Contenu'), field('value', 'Valeur', 'number', 0, 'Contenu'), commonColor],
	pomodoro: [field('work', 'Travail (minutes)', 'number', 25, 'Contenu'), field('break', 'Pause (minutes)', 'number', 5, 'Contenu'), commonColor],
	embed: [field('url', 'URL', 'text', '', 'Contenu'), commonColor],
	habits: [field('habit', 'Habitude', 'text', 'Lecture', 'Contenu'), field('days', 'Nombre de jours', 'number', 28, 'Contenu'), commonColor],
	moon: [field('label', 'Libellé', 'text', 'Lune ce soir', 'Contenu'), commonColor],
	weather: [field('latitude', 'Latitude', 'number', 48.8566, 'Contenu'), field('longitude', 'Longitude', 'number', 2.3522, 'Contenu'), field('label', 'Libellé', 'text', 'Paris', 'Contenu'), commonColor],
	calendar: [field('folder', 'Dossier', 'text', 'Daily', 'Contenu'), field('format', 'Format de date', 'text', 'YYYY-MM-DD', 'Contenu'), commonColor],
	ambient: [field('folder', 'Dossier audio', 'text', 'Audio/Ambient', 'Contenu'), commonColor],
	calculator: [commonColor, commonSize],
};
