import { WidgetContext } from '../types';

export type TimeFormat = '12' | '24';
export type HoursMode = 'auto' | 'show' | 'hide';

export interface TimeDisplayOptions { format: TimeFormat; ampm: boolean; leadingZero: boolean; timezone: string; showSeconds: boolean; hours: HoursMode; }
export interface TimeParts { hours: number; minutes: number; seconds: number; ampm: string; }

export function parseBoolean(value: unknown, fallback: boolean): boolean { if (typeof value === 'boolean') return value; if (typeof value === 'string' && /^(true|false)$/i.test(value)) return value.toLowerCase() === 'true'; return fallback; }
export function parseNumber(value: unknown, fallback: number, min = -Infinity, max = Infinity): number { const parsed = Number(value); return Number.isFinite(parsed) ? Math.min(max, Math.max(min, parsed)) : fallback; }
export function parseDuration(value: unknown): number { const raw = typeof value === 'string' || typeof value === 'number' ? String(value).trim() : ''; const clock = raw.match(/^(\d+):(\d{2})(?::(\d{2}))?$/); if (clock) return (Number(clock[1]) * 3600 + Number(clock[2]) * 60 + Number(clock[3] ?? 0)) * 1000; let total = 0; for (const match of raw.matchAll(/(\d+(?:\.\d+)?)\s*([hms])/gi)) { const unit = match[2]?.toLowerCase(); total += Number(match[1]) * ({ h: 3600000, m: 60000, s: 1000 }[unit ?? ''] ?? 0); } return total; }
export function timeParts(date: Date, options: TimeDisplayOptions): TimeParts { const formatter = new Intl.DateTimeFormat('en-US', { timeZone: options.timezone === 'local' ? undefined : options.timezone, hour: 'numeric', minute: 'numeric', second: 'numeric', hour12: options.format === '12' }); const parts = Object.fromEntries(formatter.formatToParts(date).map((part) => [part.type, part.value])); return { hours: Number(parts.hour ?? 0), minutes: Number(parts.minute ?? 0), seconds: Number(parts.second ?? 0), ampm: parts.dayPeriod ?? '' }; }
export function formatElapsed(milliseconds: number, options: Pick<TimeDisplayOptions, 'showSeconds' | 'hours'>): string[] { const totalSeconds = Math.max(0, Math.floor(milliseconds / 1000)); const seconds = totalSeconds % 60; const totalMinutes = options.showSeconds ? Math.floor(totalSeconds / 60) : Math.ceil(totalSeconds / 60); const hours = Math.floor(totalMinutes / 60); const minutes = totalMinutes % 60; const values = options.hours === 'hide' || (options.hours === 'auto' && hours === 0) ? [options.hours === 'hide' ? totalMinutes : minutes] : [hours, minutes]; return [...values.map((value) => String(value).padStart(2, '0')), ...(options.showSeconds ? [String(seconds).padStart(2, '0')] : [])]; }
export function updateEvery(options: Pick<TimeDisplayOptions, 'showSeconds'>): number { return options.showSeconds ? 1000 : 60000; }
export function stateKey(ctx: WidgetContext, id: string | undefined, fallback: string): string { return `flipclock:${id || `${ctx.sourcePath ?? fallback}:${ctx.blockRank ?? 0}`}`; }
export async function notifyFinish(ctx: WidgetContext, mode: string): Promise<void> { if (mode === 'notice' || mode === 'both') { const { Notice } = await import('obsidian'); new Notice('Le minuteur est terminé.'); } if (mode === 'sound' || mode === 'both') { const AudioContextClass = window.AudioContext ?? (window as typeof window & { webkitAudioContext?: typeof AudioContext }).webkitAudioContext; if (!AudioContextClass) return; const audio = new AudioContextClass(); const oscillator = audio.createOscillator(); const gain = audio.createGain(); oscillator.connect(gain); gain.connect(audio.destination); oscillator.frequency.value = 880; gain.gain.value = .08; oscillator.start(); oscillator.stop(audio.currentTime + .18); } }
